CREATE TABLE urls (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      short_code VARCHAR(16) NOT NULL UNIQUE,
                      original_url TEXT NOT NULL,
                      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);